name: sinners ftp test 

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USERNAME }}
        server: ${{ vars.FTP_SERVER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_path: './*'
        remote_path: ${{ vars.FTP_SERVER_DIR }}
        sftp_only: true