name: sinners ftp test 

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: milanmk/actions-file-deployer@master
      with:
        remote-host: ${{ secrets.FTP_SERVER }}
        remote-user: ${{ secrets.FTP_USERNAME }}
        remote-password: ${{ secrets.FTP_PASSWORD }}
        remote-path: ${{ secrets.FTP_SERVER_DIR }}
        remote-protocol: "sftp"